name: finvu_flutter_sdk_internal
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://www.finvu.in/
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  finvu_flutter_sdk_core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^14.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.finvu.finvu_flutter_sdk_internal
        pluginClass: FinvuFlutterSdkInternalPlugin
      ios:
        pluginClass: FinvuFlutterSdkInternalPlugin
